### ISSUE TITLE
Tu-Szu-Chi 文章

### ISSUE THREAD

**Issue by jackypan1989** [sovmedcare/hexo#1]
- [x] React lifecycle
- [x] High Order Component
- [x] inline function optimization in react
- [x] Immutable.js
- [x] Pointfree-Javascript
- [x] Function Currying
- [x] RxJS - Observable
- [x] learnrx (選至少五個範例)
- [x] 一行 redux 在 rxjs 上的實作
- [x] hot vs cold observable
- [ ] coroutine and channel in JS
- [ ] observable flow control
